[package]
name = "tetanos"
version = "0.1.0"
edition = "2021"

[build-dependencies]
nasm-rs = "0.3.0"

[dependencies]
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
