[build]
target = "x86_64-unknown-none"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.x86_64-unknown-none]
rustflags = ["-C", "relocation-model=static"]